name: Bug report
description: Report a defect with repro steps
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
